# PCA

## Principal components

In [1]:
import numpy as np

m = 60
X = np.zeros((m, 3))  # initialize 3D dataset
np.random.seed(42)
angles = (np.random.rand(m) ** 3 + 0.5) * 2 * np.pi  # uneven distribution
X[:, 0], X[:, 1] = np.cos(angles), np.sin(angles) * 0.5  # oval
X += 0.28 * np.random.randn(m, 3)  # add more noise
X += [0.2, 0, 0.2]  # shift a bit

X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt[0]
c2 = Vt[1]

In [2]:
X_centered

array([[-8.64181597e-01, -3.07845752e-01, -1.05933398e-01],
       [ 1.57721818e-01,  5.38636990e-01, -4.70605785e-01],
       [ 1.36585411e+00, -3.65356467e-01, -1.66492702e-01],
       [ 4.46201875e-01, -1.43181221e-01,  2.83803892e-01],
       [-7.38888963e-01, -4.27193977e-02,  1.15799219e-01],
       [-2.30755685e-01, -9.03031880e-02, -2.89390552e-02],
       [-8.13965778e-01, -2.79763468e-01,  2.50552689e-01],
       [ 1.46405987e+00,  4.39873812e-01,  3.04034670e-01],
       [ 3.92472299e-01, -6.14267088e-01,  1.24236228e-01],
       [ 1.53938473e+00, -3.49310966e-01,  4.61145682e-01],
       [-1.23772137e+00,  2.85895304e-01,  4.74186374e-02],
       [-4.40287501e-01,  3.42950410e-01, -5.33473838e-01],
       [ 1.31996822e+00,  3.87940018e-01,  4.36855791e-01],
       [-6.47499654e-01, -2.00647438e-01, -1.17446514e-01],
       [-2.47166970e-01,  1.28960090e-01, -1.25287399e-01],
       [-3.59726697e-01,  6.35954046e-02,  2.94266056e-01],
       [-6.85153638e-01, -1.23966971e-01

In [3]:
c1, c2

(array([0.99904597, 0.01845472, 0.03957997]),
 array([-0.02013014,  0.9988997 ,  0.04235772]))

## Projecting down to d dimensions

In [4]:
Vt[:2].T

array([[ 0.99904597, -0.02013014],
       [ 0.01845472,  0.9988997 ],
       [ 0.03957997,  0.04235772]])

$X_{d-proj} = XW_d$, where $W_d$ is the matrix containing the first $d$ columns of $V$.

In [5]:
W2 = Vt[:2].T
X2D = X_centered @ W2
X2D

array([[-8.73231190e-01, -2.94598030e-01],
       [ 1.48885182e-01,  5.14935573e-01],
       [ 1.35121872e+00, -3.99501548e-01],
       [ 4.54366763e-01, -1.39984497e-01],
       [-7.34389086e-01, -2.28934648e-02],
       [-2.33347464e-01, -8.67844755e-02],
       [-8.08435321e-01, -2.52457557e-01],
       [ 1.48281454e+00,  4.22796305e-01],
       [ 3.85679006e-01, -6.16229365e-01],
       [ 1.54972180e+00, -3.60381563e-01],
       [-1.22938760e+00,  3.12504780e-01],
       [-4.54653275e-01,  3.28839370e-01],
       [ 1.34315899e+00,  3.79446240e-01],
       [-6.55233341e-01, -1.92367174e-01],
       [-2.49510114e-01,  1.28486810e-01],
       [-3.46562831e-01,  8.32312189e-02],
       [-6.90221113e-01, -1.13712645e-01],
       [-5.29757591e-01, -2.40403321e-01],
       [-3.96344855e-01, -2.60334107e-01],
       [-6.19519220e-01, -1.13588889e-01],
       [ 3.34910399e-01, -3.09476565e-01],
       [-4.52441114e-01,  1.28501562e-01],
       [-1.02718730e+00, -7.20555799e-03],
       [ 2.

## Same as before, but using scikit-learn

In [6]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)
X2D

array([[-8.73231190e-01,  2.94598030e-01],
       [ 1.48885182e-01, -5.14935573e-01],
       [ 1.35121872e+00,  3.99501548e-01],
       [ 4.54366763e-01,  1.39984497e-01],
       [-7.34389086e-01,  2.28934648e-02],
       [-2.33347464e-01,  8.67844755e-02],
       [-8.08435321e-01,  2.52457557e-01],
       [ 1.48281454e+00, -4.22796305e-01],
       [ 3.85679006e-01,  6.16229365e-01],
       [ 1.54972180e+00,  3.60381563e-01],
       [-1.22938760e+00, -3.12504780e-01],
       [-4.54653275e-01, -3.28839370e-01],
       [ 1.34315899e+00, -3.79446240e-01],
       [-6.55233341e-01,  1.92367174e-01],
       [-2.49510114e-01, -1.28486810e-01],
       [-3.46562831e-01, -8.32312189e-02],
       [-6.90221113e-01,  1.13712645e-01],
       [-5.29757591e-01,  2.40403321e-01],
       [-3.96344855e-01,  2.60334107e-01],
       [-6.19519220e-01,  1.13588889e-01],
       [ 3.34910399e-01,  3.09476565e-01],
       [-4.52441114e-01, -1.28501562e-01],
       [-1.02718730e+00,  7.20555799e-03],
       [ 2.

## Explained variance ratio

In [7]:
pca.explained_variance_ratio_

array([0.7578477 , 0.15186921])

## Choosing the right number of dimensions

In [8]:
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', as_frame=False)
X_train, y_train = mnist.data[:60_000], mnist.target[:60_000]
X_test, y_test = mnist.data[60_000:], mnist.target[60_000:]

pca = PCA()
pca.fit(X_train)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

In [9]:
d

154

In [10]:
X_full = pca.fit_transform(X_train)
X_full.shape

(60000, 784)

In [11]:
pca = PCA(n_components=0.95) # Instead of setting the componentes to d, set the percentage of the variance we want to preserve.
X_reduced = pca.fit_transform(X_train)

In [12]:
X_reduced.shape

(60000, 154)

In [13]:
pca.n_components_

154

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import make_pipeline

clf = make_pipeline(
    PCA(random_state=42),
    RandomForestClassifier(random_state=42),
)
param_distrib = {
    "pca__n_components": np.arange(10, 80),
    "randomforestclassifier__n_estimators": np.arange(50, 500),
}
rnd_search = RandomizedSearchCV(clf, param_distrib, n_iter=10, cv=3, random_state=42)
rnd_search.fit(X_train[:1000], y_train[:1000])

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('pca', PCA(random_state=42)),
                                             ('randomforestclassifier',
                                              RandomForestClassifier(random_state=42))]),
                   param_distributions={'pca__n_components': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       6...
       414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
       427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
       440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
       453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
       466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478,
       479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499])},
                   random_state=42)

In [15]:
rnd_search.best_params_

{'randomforestclassifier__n_estimators': 465, 'pca__n_components': 23}

In [20]:
X_recovered = pca.inverse_transform(X_reduced)
X_recovered.shape

(60000, 784)

## Randomized PCA

In [21]:
rnd_pca = PCA(n_components=154, svd_solver="randomized", random_state=42)
X_reduced = rnd_pca.fit_transform(X_train)
X_reduced.shape

(60000, 154)

## Incremental PCA

In [22]:
from sklearn.decomposition import IncrementalPCA

n_batches = 100
inc_pca = IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_train, n_batches):
    inc_pca.partial_fit(X_batch)

X_reduced = inc_pca.transform(X_train)

In [23]:
X_reduced.shape

(60000, 154)

### mmap

In [25]:
# Simulate the data coming from a file and mmap it

# First create the file
filename = "datasets/my_mnist.mmap"
X_mmap = np.memmap(filename, dtype="float32", mode="write", shape=X_train.shape)
X_mmap[:] = X_train # Could be a loop instead, saving the data chunk by chunk
X_mmap.flush()

In [26]:
# Read the file
X_mmap = np.memmap(filename, dtype="float32", mode="readonly").reshape(-1, 784)
batch_size = X_mmap.shape[0] // n_batches
inc_pca = IncrementalPCA(n_components=154, batch_size=batch_size)
inc_pca.fit(X_mmap)

IncrementalPCA(batch_size=600, n_components=154)

# Random projection